name: traicon
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - pip:
    - python-dotenv
    - mkdocs
    - openai
    - anthropic
    - pydantic
    - pydantic-settings
    - instructor
    - requests
    - langfuse
    - tiktoken
    - pickle-function-cache
    - streamlit
    - -e .